name: CI
on:
  push:
    branches: main
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'

  pull_request:
  workflow_dispatch:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/NCLnclNCL/android_kernel_xiaomi_vince-3.18
          kernel-dir: msm-4.19
          kernel-branch: vince-oreo-mr1
          config: vince-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          other-gcc64-url: https://github.com/gcc-mirror/gcc
          other-gcc64-branch: master
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/5ec1cff/KernelSU
          ksu-version: next
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
